-- MySQL Script generated by MySQL Workbench
-- Mon Jun 15 13:38:08 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyecto_clinica2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto_clinica2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto_clinica2` ;
USE `proyecto_clinica2` ;

-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`personas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `nombres` VARCHAR(100) NOT NULL DEFAULT 'NO IDENTIFICADO',
  `apellidos` VARCHAR(100) NOT NULL DEFAULT 'NO IDENTIFICADO',
  `genero` ENUM('MASCULINO', 'FEMENINO', 'OTRO', 'NO_ESPECIFICA') NOT NULL DEFAULT 'NO_ESPECIFICA',
  `fecha_nacimiento` DATE NOT NULL DEFAULT '1900-01-01',
  `telefono` VARCHAR(15) NOT NULL DEFAULT '0000000000',
  `direccion` VARCHAR(200) NOT NULL DEFAULT 'NO REGISTRADA',
  `correo` VARCHAR(100) NOT NULL,
  `fecha_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tiene_identificacion` TINYINT NOT NULL DEFAULT 1,
  `estado` ENUM('ACTIVO', 'INACTIVO') NOT NULL DEFAULT 'ACTIVO',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`pacientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  `numero_historia` VARCHAR(30) NOT NULL,
  `tipo_sangre` ENUM('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', 'NO_REGISTRADO') NOT NULL DEFAULT 'NO_REGISTRADO',
  `enfermedades_cronicas` VARCHAR(300) NOT NULL DEFAULT 'NINGUNA',
  `tiene_alergias` TINYINT NOT NULL DEFAULT 0,
  `contacto_emergencia` VARCHAR(100) NOT NULL DEFAULT 'NO_REGISTRADO',
  `telefono_emergencia` VARCHAR(20) NOT NULL DEFAULT '0000000000',
  `seguro_medico` VARCHAR(150) NOT NULL DEFAULT 'PARTICULAR',
  `estado_paciente` ENUM('ACTIVO', 'INACTIVO') NOT NULL DEFAULT 'ACTIVO',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `numero_historia_UNIQUE` (`numero_historia` ASC) VISIBLE,
  INDEX `fk_pacientes_personas_idx` (`persona_id` ASC) VISIBLE,
  UNIQUE INDEX `persona_id_UNIQUE` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_pacientes_personas`
    FOREIGN KEY (`persona_id`)
    REFERENCES `proyecto_clinica2`.`personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`medicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  `numero_licencia` VARCHAR(50) NOT NULL,
  `anios_experiencia` INT UNSIGNED NOT NULL DEFAULT 0,
  `codigo_medico` VARCHAR(20) NOT NULL,
  `estado_medico` ENUM('ACTIVO', 'INACTIVO') NOT NULL DEFAULT 'ACTIVO',
  `tipo_contrato` ENUM('PLANTA', 'CONTRATO', 'MEDIO_TIEMPO', 'HONORARIOS') NOT NULL DEFAULT 'CONTRATO',
  `fecha_ingreso` DATE NOT NULL DEFAULT '1900-01-01',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `codigo_medico_UNIQUE` (`codigo_medico` ASC) VISIBLE,
  UNIQUE INDEX `numero_licencia_UNIQUE` (`numero_licencia` ASC) VISIBLE,
  INDEX `fk_medicos_personas1_idx` (`persona_id` ASC) VISIBLE,
  UNIQUE INDEX `persona_id_UNIQUE` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_medicos_personas1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `proyecto_clinica2`.`personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`especialidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_especialidad` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL DEFAULT 'NINGUNA',
  `estado_especialidad` ENUM('ACTIVA', 'INACTIVA') NOT NULL DEFAULT 'ACTIVA',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre_especialidad` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`consultorios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`consultorios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero_consultorio` VARCHAR(20) NOT NULL,
  `piso` INT UNSIGNED NOT NULL DEFAULT '1',
  `estado_consultorio` ENUM('DISPONIBLE', 'OCUPADO', 'MANTENIMIENTO') NOT NULL DEFAULT 'DISPONIBLE',
  `descripcion` VARCHAR(150) NOT NULL DEFAULT 'SIN DESCRIPCION',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `numero_consultorio_UNIQUE` (`numero_consultorio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`citas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `paciente_id` INT NOT NULL,
  `medico_id` INT NOT NULL,
  `especialidad_id` INT NOT NULL,
  `consultorio_id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `estado_cita` ENUM('PROGRAMADA', 'REPROGRAMADA', 'ATENDIDA', 'CANCELADA', 'NO_ASISTIO') NOT NULL DEFAULT 'PROGRAMADA',
  `motivo` VARCHAR(200) NOT NULL DEFAULT 'NO ESPECIFICADO',
  `tipo_cita` ENUM('PRIMERA_VEZ', 'CONTROL', 'URGENCIA') NOT NULL DEFAULT 'PRIMERA_VEZ',
  `observaciones` VARCHAR(500) NOT NULL DEFAULT 'SIN OBSERVACIONES',
  PRIMARY KEY (`id`),
  INDEX `fk_citas_pacientes1_idx` (`paciente_id` ASC) VISIBLE,
  INDEX `fk_citas_medicos1_idx` (`medico_id` ASC) VISIBLE,
  INDEX `fk_citas_especialidades1_idx` (`especialidad_id` ASC) VISIBLE,
  INDEX `fk_citas_consultorios1_idx` (`consultorio_id` ASC) VISIBLE,
  CONSTRAINT `fk_citas_pacientes1`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `proyecto_clinica2`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_citas_medicos1`
    FOREIGN KEY (`medico_id`)
    REFERENCES `proyecto_clinica2`.`medicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_citas_especialidades1`
    FOREIGN KEY (`especialidad_id`)
    REFERENCES `proyecto_clinica2`.`especialidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_citas_consultorios1`
    FOREIGN KEY (`consultorio_id`)
    REFERENCES `proyecto_clinica2`.`consultorios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`consultas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cita_id` INT NOT NULL,
  `fecha_consulta` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sintomas` VARCHAR(500) NOT NULL DEFAULT 'SIN SINTOMAS REGISTRADOS',
  `tratamiento` VARCHAR(500) NOT NULL DEFAULT 'SIN TRATAMIENTO REGISTRADO',
  `observaciones` VARCHAR(500) NOT NULL DEFAULT 'SIN OBSERVACIONES',
  `proxima_revision` DATE NOT NULL DEFAULT '1900-01-01',
  `estado_consulta` ENUM('ABIERTA', 'CERRADA', 'ANULADA') NOT NULL DEFAULT 'ABIERTA',
  PRIMARY KEY (`id`),
  INDEX `fk_consultas_citas1_idx` (`cita_id` ASC) VISIBLE,
  UNIQUE INDEX `cita_id_UNIQUE` (`cita_id` ASC) VISIBLE,
  CONSTRAINT `fk_consultas_citas1`
    FOREIGN KEY (`cita_id`)
    REFERENCES `proyecto_clinica2`.`citas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`tiposExamenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`tiposExamenes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL DEFAULT 'SIN DESCRIPCION',
  `precio_referencial` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00,
  `estado_tipo_examen` ENUM('ACTIVO', 'INACTIVO') NOT NULL DEFAULT 'ACTIVO',
  `categoria` ENUM('LABORATORIO', 'IMAGEN', 'CARDIOLOGIA', 'OTRO') NOT NULL DEFAULT 'OTRO',
  `preparacion` VARCHAR(250) NOT NULL DEFAULT 'NO REQUIERE PREPARACION',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_examen_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`examenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`examenes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `consulta_id` INT NOT NULL,
  `tipoExamen_id` INT NOT NULL,
  `fecha_solicitud` DATE NOT NULL DEFAULT '1900-01-01',
  `fecha_examen` DATE NOT NULL DEFAULT '1900-01-01',
  `fecha_resultado` DATE NOT NULL DEFAULT '1900-01-01',
  `estado_examen` ENUM('SOLICITADO', 'REALIZADO', 'ENTREGADO', 'CANCELADO') NOT NULL DEFAULT 'SOLICITADO',
  `resultado` VARCHAR(300) NOT NULL DEFAULT 'PENDIENTE',
  `costo` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00,
  `observaciones` VARCHAR(45) NOT NULL DEFAULT 'SIN OBSERVACIONES',
  PRIMARY KEY (`id`),
  INDEX `fk_examenes_consultas1_idx` (`consulta_id` ASC) VISIBLE,
  INDEX `fk_examenes_tiposExamenes1_idx` (`tipoExamen_id` ASC) VISIBLE,
  CONSTRAINT `fk_examenes_consultas1`
    FOREIGN KEY (`consulta_id`)
    REFERENCES `proyecto_clinica2`.`consultas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_examenes_tiposExamenes1`
    FOREIGN KEY (`tipoExamen_id`)
    REFERENCES `proyecto_clinica2`.`tiposExamenes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`facturas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `paciente_id` INT NOT NULL,
  `consulta_id` INT NOT NULL,
  `fecha_emision` DATE NOT NULL DEFAULT '1900-01-01',
  `total` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00,
  `monto_pagado` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00,
  `saldo_pendiente` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00,
  `estado_factura` ENUM('PENDIENTE', 'PAGADA', 'ANULADA') NOT NULL DEFAULT 'PENDIENTE',
  `detalle` VARCHAR(500) NOT NULL DEFAULT 'VER DETALLE FACTURA',
  `observaciones` VARCHAR(500) NOT NULL DEFAULT 'SIN_OBSERVACIONES',
  PRIMARY KEY (`id`),
  INDEX `fk_facturas_pacientes1_idx` (`paciente_id` ASC) VISIBLE,
  INDEX `fk_facturas_consultas1_idx` (`consulta_id` ASC) VISIBLE,
  CONSTRAINT `fk_facturas_pacientes1`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `proyecto_clinica2`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facturas_consultas1`
    FOREIGN KEY (`consulta_id`)
    REFERENCES `proyecto_clinica2`.`consultas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`medicamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`medicamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL DEFAULT 'SIN DESCRIPCION',
  `stock_actual` INT UNSIGNED NOT NULL DEFAULT 0,
  `stock_minimo` INT UNSIGNED NOT NULL DEFAULT 0,
  `presentacion` VARCHAR(100) NOT NULL DEFAULT 'NO ESPECIFICADA',
  `concentracion` VARCHAR(70) NOT NULL DEFAULT 'NO ESPECIFICADA',
  `laboratorio` VARCHAR(90) NOT NULL DEFAULT 'NO ESPECIFICADO',
  `precio_unitario` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00,
  `fecha_vencimiento` DATE NOT NULL DEFAULT '1900-01-01',
  `estado` ENUM('DISPONIBLE', 'AGOTADO', 'SUSPENDIDO') NOT NULL DEFAULT 'DISPONIBLE',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`recetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`recetas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `consulta_id` INT NOT NULL,
  `fecha_emision` DATE NOT NULL DEFAULT '1900-01-01',
  `indicaciones_generales` VARCHAR(500) NOT NULL DEFAULT 'SIN INDICACIONES',
  `estado_receta` ENUM('ACTIVA', 'FINALIZADA', 'ANULADA') NOT NULL DEFAULT 'ACTIVA',
  `observaciones` VARCHAR(500) NOT NULL DEFAULT 'SIN OBSERVACIONES',
  PRIMARY KEY (`id`),
  INDEX `fk_recetas_consultas1_idx` (`consulta_id` ASC) VISIBLE,
  CONSTRAINT `fk_recetas_consultas1`
    FOREIGN KEY (`consulta_id`)
    REFERENCES `proyecto_clinica2`.`consultas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`alergias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`alergias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `tipo` ENUM('MEDICAMENTO', 'ALIMENTO', 'AMBIENTAL', 'OTRA') NOT NULL DEFAULT 'OTRA',
  `descripcion` VARCHAR(500) NOT NULL DEFAULT 'SIN DESCRIPCION',
  `gravedad` ENUM('ALTA', 'MEDIA', 'BAJA') NOT NULL DEFAULT 'BAJA',
  `estado` ENUM('ACTIVA', 'INACTIVA') NOT NULL DEFAULT 'ACTIVA',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_alergia_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`pacientes_alergias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`pacientes_alergias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `alergia_id` INT NOT NULL,
  `paciente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_alergias_pacientes_alergias1_idx` (`alergia_id` ASC) VISIBLE,
  INDEX `fk_alergias_pacientes_pacientes1_idx` (`paciente_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_paciente_alergia` (`alergia_id` ASC, `paciente_id` ASC) VISIBLE,
  CONSTRAINT `fk_alergias_pacientes_alergias1`
    FOREIGN KEY (`alergia_id`)
    REFERENCES `proyecto_clinica2`.`alergias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alergias_pacientes_pacientes1`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `proyecto_clinica2`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`serviciosClinicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`serviciosClinicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_servicio` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL DEFAULT 'SIN DESCRIPCION',
  `costo` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00,
  `tipo_servicio` ENUM('CONSULTA', 'PROCEDIMIENTO', 'LABORATORIO', 'OTRO') NOT NULL DEFAULT 'OTRO',
  `estado_servicio` ENUM('ACTIVO', 'INACTIVO') NOT NULL DEFAULT 'ACTIVO',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_servicio_UNIQUE` (`nombre_servicio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`detalleFactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`detalleFactura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `factura_id` INT NOT NULL,
  `servicioClinico_id` INT NULL,
  `examen_id` INT NULL,
  `descripcion` VARCHAR(150) NOT NULL DEFAULT 'SIN_DESCRIPCION',
  `cantidad` INT UNSIGNED NOT NULL,
  `precio_unitario` DECIMAL(10,2) UNSIGNED NOT NULL,
  `subtotal` DECIMAL(10,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalleFactura_facturas1_idx` (`factura_id` ASC) VISIBLE,
  INDEX `fk_detalleFactura_serviciosClinicos1_idx` (`servicioClinico_id` ASC) VISIBLE,
  INDEX `fk_detalleFactura_examenes1_idx` (`examen_id` ASC) VISIBLE,
  CONSTRAINT `fk_detalleFactura_facturas1`
    FOREIGN KEY (`factura_id`)
    REFERENCES `proyecto_clinica2`.`facturas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleFactura_serviciosClinicos1`
    FOREIGN KEY (`servicioClinico_id`)
    REFERENCES `proyecto_clinica2`.`serviciosClinicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleFactura_examenes1`
    FOREIGN KEY (`examen_id`)
    REFERENCES `proyecto_clinica2`.`examenes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`diagnosticos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`diagnosticos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `consulta_id` INT NOT NULL,
  `nombre_diagnostico` VARCHAR(200) NOT NULL DEFAULT 'SIN DIAGNOSTICO',
  `descripcion` VARCHAR(500) NOT NULL DEFAULT 'SIN DESCRIPCION',
  `gravedad` ENUM('ALTA', 'MEDIA', 'BAJA') NOT NULL DEFAULT 'BAJA',
  `fecha_diagnostico` DATE NOT NULL DEFAULT '1900-01-01',
  `observaciones` VARCHAR(500) NOT NULL DEFAULT 'SIN OBSERVACIONES',
  `estado_diagnostico` ENUM('ACTIVO', 'DESCARTADO', 'EN_SEGUIMIENTO') NOT NULL DEFAULT 'ACTIVO',
  PRIMARY KEY (`id`),
  INDEX `fk_diagnosticos_consultas1_idx` (`consulta_id` ASC) VISIBLE,
  CONSTRAINT `fk_diagnosticos_consultas1`
    FOREIGN KEY (`consulta_id`)
    REFERENCES `proyecto_clinica2`.`consultas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`historiasClinicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`historiasClinicas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `paciente_id` INT NOT NULL,
  `consulta_id` INT NULL,
  `fecha_registro` DATE NOT NULL DEFAULT '1900-01-01',
  `tipo_registro` ENUM('ANTECEDENTE', 'CONSULTA', 'OBSERVACION', 'ALERGIA', 'EXAMEN') NOT NULL DEFAULT 'OBSERVACION',
  `descripcion` VARCHAR(500) NOT NULL DEFAULT 'SIN DESCRIPCION',
  `antecedentes` VARCHAR(500) NOT NULL DEFAULT 'SIN ANTECEDENTES',
  `observaciones` VARCHAR(500) NOT NULL DEFAULT 'SIN OBSERVACIONES',
  `estado_historia` ENUM('ACTIVA', 'ARCHIVADA') NOT NULL DEFAULT 'ACTIVA',
  PRIMARY KEY (`id`),
  INDEX `fk_historiasClinicas_pacientes1_idx` (`paciente_id` ASC) VISIBLE,
  INDEX `fk_historiasClinicas_consultas1_idx` (`consulta_id` ASC) VISIBLE,
  CONSTRAINT `fk_historiasClinicas_pacientes1`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `proyecto_clinica2`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historiasClinicas_consultas1`
    FOREIGN KEY (`consulta_id`)
    REFERENCES `proyecto_clinica2`.`consultas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`horariosMedicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`horariosMedicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `medico_id` INT NOT NULL,
  `dia_semana` ENUM('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO') NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fin` TIME NOT NULL,
  `horas_extra` INT UNSIGNED NOT NULL DEFAULT 0,
  `estado_horario` ENUM('ACTIVO', 'INACTIVO') NOT NULL DEFAULT 'ACTIVO',
  PRIMARY KEY (`id`),
  INDEX `fk_horariosMedicos_medicos1_idx` (`medico_id` ASC) VISIBLE,
  CONSTRAINT `fk_horariosMedicos_medicos1`
    FOREIGN KEY (`medico_id`)
    REFERENCES `proyecto_clinica2`.`medicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`medicos_especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`medicos_especialidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `medico_id` INT NOT NULL,
  `especialidad_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_medicos_especialidades_medicos1_idx` (`medico_id` ASC) VISIBLE,
  INDEX `fk_medicos_especialidades_especialidades1_idx` (`especialidad_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_medico_especialidad` (`medico_id` ASC, `especialidad_id` ASC) INVISIBLE,
  CONSTRAINT `fk_medicos_especialidades_medicos1`
    FOREIGN KEY (`medico_id`)
    REFERENCES `proyecto_clinica2`.`medicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicos_especialidades_especialidades1`
    FOREIGN KEY (`especialidad_id`)
    REFERENCES `proyecto_clinica2`.`especialidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`pagos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `factura_id` INT NOT NULL,
  `fecha_pago` DATE NOT NULL DEFAULT '1900-01-01',
  `monto` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00,
  `metodo_pago` ENUM('EFECTIVO', 'TARJETA', 'TRANSFERENCIA') NOT NULL DEFAULT 'EFECTIVO',
  `referencia_pago` VARCHAR(45) NOT NULL DEFAULT 'SIN REFERENCIA',
  `estado_pago` ENUM('CONFIRMADO', 'PENDIENTE', 'ANULADO') NOT NULL DEFAULT 'PENDIENTE',
  `observacion` VARCHAR(200) NOT NULL DEFAULT 'SIN OBSERVACION',
  PRIMARY KEY (`id`),
  INDEX `fk_pagos_facturas1_idx` (`factura_id` ASC) VISIBLE,
  CONSTRAINT `fk_pagos_facturas1`
    FOREIGN KEY (`factura_id`)
    REFERENCES `proyecto_clinica2`.`facturas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`personalClinico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`personalClinico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  `cargo` ENUM('ENFERMERO', 'LABORATORISTA', 'RECEPCIONISTA', 'ADMINISTRATIVO', 'LIMPIEZA', 'AUXILIAR') NOT NULL DEFAULT 'AUXILIAR',
  `turno` ENUM('MANANA', 'TARDE', 'NOCHE') NOT NULL DEFAULT 'MANANA',
  `area_trabajo` ENUM('ENFERMERIA', 'LABORATORIO', 'RECEPCION', 'LIMPIEZA', 'ADMINISTRACION', 'GENERAL') NOT NULL DEFAULT 'GENERAL',
  `fecha_ingreso` DATE NOT NULL DEFAULT '1900-01-01',
  `estado_personal` ENUM('ACTIVO', 'INACTIVO') NOT NULL DEFAULT 'ACTIVO',
  PRIMARY KEY (`id`),
  INDEX `fk_personalClinico_personas1_idx` (`persona_id` ASC) VISIBLE,
  UNIQUE INDEX `persona_id_UNIQUE` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_personalClinico_personas1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `proyecto_clinica2`.`personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_clinica2`.`recetas_medicamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_clinica2`.`recetas_medicamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `receta_id` INT NOT NULL,
  `medicamento_id` INT NOT NULL,
  `dosis` VARCHAR(100) NOT NULL,
  `frecuencia` VARCHAR(100) NOT NULL,
  `duracion` VARCHAR(100) NOT NULL,
  `cantidad` INT UNSIGNED NOT NULL,
  `instrucciones` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recetas_medicamentos_recetas1_idx` (`receta_id` ASC) VISIBLE,
  INDEX `fk_recetas_medicamentos_medicamentos1_idx` (`medicamento_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_receta_medicamento` (`receta_id` ASC, `medicamento_id` ASC) VISIBLE,
  CONSTRAINT `fk_recetas_medicamentos_recetas1`
    FOREIGN KEY (`receta_id`)
    REFERENCES `proyecto_clinica2`.`recetas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recetas_medicamentos_medicamentos1`
    FOREIGN KEY (`medicamento_id`)
    REFERENCES `proyecto_clinica2`.`medicamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
